# Parameter space exploration
ERRORS_PARAMETER_SPACE_BEGIN, ERRORS_PARAMETER_SPACE_END = 10**-2, 0.99
ERRORS_PARAMETER_SPACE_NUM = 20
FEATURE_DIST_VARIANCE = 1.0
PER_PARAMETER = 100

# Bout diuration distributions
POWER_LAW_ALPHA = 1.5
EXPONENTIAL_LAMBDA = 0.01

# Other
NUM_BOUTS = 1000
