# Parameter space exploration
ERRORS_PARAMETER_SPACE_BEGIN, ERRORS_PARAMETER_SPACE_END = 10**-2, 0.99
ERRORS_PARAMETER_SPACE_NUM = 5
FEATURE_DIST_VARIANCE = 1.0
PER_PARAMETER = 5

# Bout diuration distributions
POWER_LAW_ALPHA = 1.75
EXPONENTIAL_LAMBDA = 0.1

# Other
NUM_BOUTS = 1000
